export const messages: {[key:string]: string} = {
	"required": "Das Feld '{field}' wird benötigt.",
	"string": "Das Feld '{field}' muss ein Text sein.",
	"stringEmpty": "Das Feld '{field}' darf nicht leer sein.",
	"stringMin": "Das Feld '{field}' muss {expected} Zeichen oder länger sein.",
	"stringMax": "Das Feld '{field}' muss {expected} Zeichen oder kürzer sein.",
	"stringLength": "Das Feld '{field}' muss {expected} Zeichen lang sein.",
	"stringPattern": "Das Feld '{field}' stimmt nicht mit dem benötigten Muster überein.",
	"stringContains": "Das Feld '{field}' muss '{expected}' enthalten.",
	"stringEnum": "Das Feld '{field}' entspricht nicht einem der erlaubten Werten.",
	"stringNumeric": "Das Feld '{field}' muss eine numerische Zeichenfolge sein.",
	"stringAlpha": "Das Feld '{field}' muss eine alphabetische Zeichenfolge sein.",
	"stringAlphanum": "Das Feld '{field}' muss eine alpha-numerische Zeichenfolge sein.",
	"stringAlphadash": "Das Feld '{field}' muss eine Zeichefolge mit Bindestrichen sein.",
	"stringHex": "Das Feld '{field}' muss ein Hexadezimale Zeichenfolge sein.",
	"stringSingleLine": "Das Feld '{field}' darf nur aus einer Zeile bestehen.",
	"stringBase64": "Das Feld '{field}' ein base64-codierte Zeichenfolge sein.",
	"number": "Das Feld '{field}' muss eine Nummer sein.",
	"numberMin": "Das Feld '{field}' muss größer oder gleich {expected} sein.",
	"numberMax": "Das Feld '{field}' muss kleiner oder gleich {expected} sein.",
	"numberEqual": "Das Feld '{field}' muss gleich {expected} sein.",
	"numberNotEqual": "Das Feld '{field}' darf nicht gleich {expected} sein.",
	"numberInteger": "Das Feld '{field}' muss eine Ganzzahl sein.",
	"numberPositive": "Das Feld '{field}' muss eine positive Zahl sein.",
	"numberNegative": "Das Feld '{field}' muss eine negative Zahl sein.",
	"array": "Das Feld '{field}' muss ein Array sein.",
	"arrayEmpty": "Das Feld '{field}' darf kein leeres Array sein.",
	"arrayMin": "Das Feld '{field}' muss mindestens {expected} Einträge beinhalten.",
	"arrayMax": "Das Feld '{field}' muss {expected} oder weniger Einträge beinhalten.",
	"arrayLength": "Das Feld '{field}' muss {expected} Einträge beinhalten.",
	"arrayContains": "Das Feld '{field}' muss den Eintrag '{expected}' beinhalten.",
	"arrayUnique": "Der Wert '{expected}' darf im Feld '{field}' nur einmal vorkommen: '{actual}'.",
	"arrayEnum": "Der Wert '{actual}' im Feld '{field}' entspricht nicht einen dieser Werte: '{expected}'.",
	"tuple": "Das Feld '{field}' muss ein Array sein.",
	"tupleEmpty": "Das Feld '{field}' darf kein leeres Array sein.",
	"tupleLength": "Das Feld '{field}' muss mindestens {expected} Einträge beinhalten.",
	"boolean": "Das Feld '{field}' muss ein boolischer Wert sein.",
	"function": "Das Feld '{field}' muss eine Funktion sein.",
	"date": "Das Feld '{field}' muss ein Datum sein.",
	"dateMin": "Das Feld '{field}' muss größer oder gleich {expected} sein.",
	"dateMax": "Das Feld '{field}' muss kleiner oder gleich {expected} sein.",
	"forbidden": "Das Feld '{field}' ist nicht erlaubt.",
	"email": "Das Feld '{field}' muss eine gültige E-Mail-Adresse sein.",
	"emailEmpty": "Das Feld '{field}' darf nicht leer sein.",
	"emailMin": "Das Feld '{field}' muss länger oder gleich {expected} Zeichen lang sein.",
	"emailMax": "Das Feld '{field}' muss kürzer oder gleich {expected} Zeichen lang sein.",
	"url": "Das Feld '{field}' muss eine gültige URL sein.",
	"enumValue": "Das Feld '{field}' entspricht keinen der erlaubten Werte: '{expected}'.",
	"equalValue": "Das Feld '{field}' muss gleich '{expected}' sein.",
	"equalField": "Das Feld '{field}' muss dem '{expected}' Feld entsprechen.",
	"object": "Das Feld '{field}' muss ein Objekt sein.",
	"objectStrict": "Das Objekt '{field}' beinhaltet verbotene Schlüssel: '{actual}'.",
	"objectMinProps": "Das Objekt '{field}' muss mindestens {expected} Einträge beinhalten.",
	"objectMaxProps": "Das Objekt '{field}' darf nicht mehr als {expected} Einträge beinhalten.",
	"uuid": "Das Feld '{field}' muss eine gültige UUID sein.",
	"uuidVersion": "Das Feld '{field}' muss eine gültige UUID der angegebenen Version beinhalten.",
	"mac": "Das Feld '{field}' muss eine gültige MAC-Adresse beinhalten.",
	"luhn": "Das Feld '{field}' muss eine gültige Checksum sein.",
	"record": "Das Feld '{field}' muss ein Objekt sein.",
}